name: Remove all nacl rules
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - intg
          - staging
          - prod
        default: 'intg'

permissions:
  id-token: write
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/${{ github.event.inputs.environment }}-dr2-runbook-remove-all-nacl-rules
          aws-region: eu-west-2
          role-session-name: RunbookRemoveAllNaclRules
      - run: |
          pip install -r requirements-runtime.txt
          python remove_all_nacl_rules.py
          
