name: Run runbooks tests
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@2d29c2e83fbaba6554c1e0d8c0b45d2015d610b2 # v0.0.41
      - run: |
          pip install -r requirements.txt
          AWS_DEFAULT_REGION=eu-west-2 pytest
