name: Run runbooks tests
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@e7b57a3bdf7863c951cd203101c6d566986376e3 # v0.0.38
      - run: |
          pip install -r requirements.txt
          AWS_DEFAULT_REGION=eu-west-2 pytest
